#*=====================================================================*/
#*    serrano/prgm/project/hhmqtt/hhmqtt/Makefile.npm                  */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Apr 11 09:11:01 2024                          */
#*    Last change :  Tue Jun 11 08:28:42 2024 (serrano)                */
#*    Copyright   :  2024 Manuel Serrano                               */
#*    -------------------------------------------------------------    */
#*    HHMQTT - An example of MQTT apps programmed with HipHop          */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Compilers                                                        */
#*---------------------------------------------------------------------*/
ROOT=.
HOPC=$(ROOT)/node_modules/@hop/hopc/bin/hopc.mjs
HHC=$(ROOT)/node_modules/@hop/hiphop/bin/hhc.mjs

#*---------------------------------------------------------------------*/
#*    Source files ...                                                 */
#*---------------------------------------------------------------------*/
HHMQTT_JS=utils.js config.js hhmqtt.js
HHMQTT_HH=click.hh.js clicktmt.hh.js

SOURCES=$(HHMQTT_JS:%=src/%) $(HHMQTT_HH:%=src/%) 
OBJECTS=$(HHMQTT_JS:%.js=dist/%.js) $(HHMQTT_HH:%.hh.js=dist/%.js)

#*---------------------------------------------------------------------*/
#*    Public targets                                                   */
#*---------------------------------------------------------------------*/
build: dist
	$(MAKE) -f Makefile.npm $(OBJECTS)

clean:: 
	rm -f $(OBJECTS)

#*---------------------------------------------------------------------*/
#*    Compilation rules and dependencies                               */
#*---------------------------------------------------------------------*/
dist/%.js: src/%.js
	cp $< $@

src/%.js: src/%.hh.js
	$(HHC) -o $@ $<

dist:
	mkdir -p dist
