#*=====================================================================*/
#*    serrano/prgm/project/hhmqtt/hhmqtt.ts/Makefile.npm               */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Apr 11 09:11:01 2024                          */
#*    Last change :  Tue Jun 11 07:47:54 2024 (serrano)                */
#*    Copyright   :  2024 Manuel Serrano                               */
#*    -------------------------------------------------------------    */
#*    HHMQTT - An example of MQTT apps programmed with HipHop          */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Compilers                                                        */
#*---------------------------------------------------------------------*/
ROOT=.
HOPC=$(ROOT)/node_modules/@hop/hopc/bin/hopc.mjs
HHC=$(ROOT)/node_modules/@hop/hiphop/bin/hhc.mjs

#*---------------------------------------------------------------------*/
#*    Source files ...                                                 */
#*---------------------------------------------------------------------*/
HHMQTT_TS=utils.ts config.ts hhmqtt.ts
HHMQTT_HH=click.hh.ts clicktmt.hh.ts

SOURCES=$(HHMQTT_TS:%=src/%) $(HHMQTT_HH:%=src/%) 
OBJECTS=$(HHMQTT_TS:%.ts=dist/%.js) $(HHMQTT_HH:%.hh.ts=dist/%.js)

#*---------------------------------------------------------------------*/
#*    Public targets                                                   */
#*---------------------------------------------------------------------*/
build: dist
	$(MAKE) $(OBJECTS)

clean:: 
	rm -f $(OBJECTS)

#*---------------------------------------------------------------------*/
#*    Compilation rules and dependencies                               */
#*---------------------------------------------------------------------*/
.SUFFIXES: .ts .js .hh.ts

dist/%.js: src/%.ts
	$(HOPC) $(HFLAGS) -o $@ $<

src/%.ts: src/%.hh.ts
	$(HHC) -o $@ $<

dist:
	mkdir -p dist
